### PR TITLE
Managed Identity support added

### PR DESCRIPTION
**Pull request by jhisc**
Added support for using managed identity authentication.
Replacing the Service principal bearer call for the Metadata API service.

### CODE REVIEW

**Comment by lordozb** [comment]
Hello @jhisc 
Please don't make changes to index.js file. It is the compiled javascript file which is compiled using ncc compiler and is auto generated. You can make changes to utils/deploy_utils.ts and then use ncc to generate a new index.js file.

**Comment by jhisc** [comment]
Thank you 

I have updated the typescript files and recompiled using:

`ncc build build_and_deploy/index.js`

**Comment by lordozb** [comment]
Hello @jhisc 
Can you please resolve the conflicts and then we can go ahead and merge it.
Thank you for contributing to Synapse workspace deployment.

**Comment by jhisc** [comment]
Thank you @lordozb
I've resolved the conflicts and re-complied using the master branch

**Pull request merged**
