### PR TITLE
Treat AutoResolveIntegrationRuntime as a default artifact

### PR DESCRIPTION
**Pull request by owenfarrell**
When creating a new Synapse Workspace, an Integration Runtime named `AutoResolveIntegrationRuntime` is automatically created.

> The workspace manages the integration runtime in Azure to connect to required data source/destination or external compute in public network. The compute resource is elastic allocated based on performance requirement of activities.

### CODE REVIEW

**Comment by owenfarrell** [comment]
@lordozb - Thoughts?

**Comment by lordozb** [comment]
Hello @owenfarrell 
Sorry for delay in getting back.

Changes will also be required in [Here](https://github.com/Azure/Synapse-workspace-deployment/blob/093cd50e25f16943cad940b275b9279e11de663f/build_and_deploy/utils/common_utils.ts#L13) because integration runtime is of type Microsoft.Synapse/workspaces/integrationRuntimes.

Can you please also add some positive and negative unit tests [Here](https://github.com/Azure/Synapse-workspace-deployment/blob/093cd50e25f16943cad940b275b9279e11de663f/build_and_deploy/test/common_utils_tests.ts#L17)

**Comment by lordozb** [comment]
Hello @owenfarrell 
Thank you for contributing to the project. We have asked our partner team which manages integration runtime to let us know if skipping autoresolve IR will cause any issue or not. We are waiting for their response.

**Comment by owenfarrell** [comment]
@lordozb - What's the verdict?

**Comment by lordozb** [comment]
Hello @owenfarrell 
Apologies for delay in getting back. We can go ahead and mark it as a default artifact. However, due to the recent commit there has been some merge conflicts. If you can resolve the conflicts I can go ahead and merge the PR. If you are unavailable I can resolve the conflicts and merge your PR.

**Comment by owenfarrell** [comment]
@lordozb - I can resolve the conflicts. But I have a couple questions about #28.

1. Did you just copy the `DefaultArtifact` class that I added here and paste it in to your PR? Or is there something genuinely different?
2.  Is there a way to selectively disable the deployment of managed private endpoints? Your PR (as written) seems to duplicate some automation capabilities that exist elsewhere (namely https://github.com/hashicorp/terraform-provider-azurerm/pull/9260). And Terraform is adding more a la carte capabilities for Synapse artifacts, courtesy of @ms-henglu.
  I guess my question really is: is **_this_** CI/CD plugin trying to complement other automation tools? or compete with them?

**Comment by lordozb** [comment]
@owenfarrell Currently, the code deploys all the artifacts in the template. There is no way to do selective deployment as of now.

**Comment by owenfarrell** [comment]
Closing this PR since the code was copied/committed elsewhere

**Pull request closed without merging**
